FROM node:22-alpine AS dependencies
WORKDIR /app
RUN corepack enable
COPY package.json pnpm-lock.yaml ./
COPY patches ./patches
RUN pnpm install --frozen-lockfile

FROM node:22-alpine AS builder
WORKDIR /app
RUN corepack enable
COPY --from=dependencies /app/node_modules ./node_modules
COPY . .
ARG NEXT_PUBLIC_APP_URL=http://localhost:3000
ARG NEXT_PUBLIC_API_URL=http://localhost:4000
ARG NEXT_PUBLIC_CHAIN_ID=46630
ARG NEXT_PUBLIC_CHAIN_NAME="Robinhood Chain Testnet"
ARG NEXT_PUBLIC_CHAIN_RPC_URL=https://rpc.testnet.chain.robinhood.com
ARG NEXT_PUBLIC_CHAIN_EXPLORER_NAME="Robinhood Testnet Explorer"
ARG NEXT_PUBLIC_CHAIN_EXPLORER_URL=https://explorer.testnet.chain.robinhood.com
ARG NEXT_PUBLIC_CHAIN_TESTNET=true
ARG NEXT_PUBLIC_WALLETCONNECT_PROJECT_ID=""
ARG NEXT_PUBLIC_XBID_FACTORY_ADDRESS=0x8f9208FD358c62FB4052e4C2FBbCA3152A17E4b6
ARG NEXT_PUBLIC_XBID_REGISTRY_ADDRESS=0x0B68fD82965Fd853907CA4E2f7E6E6d478Aaef8b
ARG NEXT_PUBLIC_XBID_RISK_CONTROLLER_ADDRESS=0xfeebdbB42de39B95f8dE5FcdBDd11e986443c278
ARG NEXT_PUBLIC_XBID_FEE_VAULT_ADDRESS=0x82D9159cB488175cAcdcD145A7285d80563e69d0
ARG NEXT_PUBLIC_XBID_SETTLEMENT_TOKEN_ADDRESS=0xAc80194dc1aE8eF52df73e7e1864fB3C62290fe0
ARG NEXT_PUBLIC_DEFAULT_CONTEST_ID=0xb73517e2deacfc81a60953d1545f6602b186483d3e9b59fc43a5a8e75497513d
ENV NEXT_TELEMETRY_DISABLED=1
ENV NEXT_PUBLIC_APP_URL=$NEXT_PUBLIC_APP_URL
ENV NEXT_PUBLIC_API_URL=$NEXT_PUBLIC_API_URL
ENV NEXT_PUBLIC_CHAIN_ID=$NEXT_PUBLIC_CHAIN_ID
ENV NEXT_PUBLIC_CHAIN_NAME=$NEXT_PUBLIC_CHAIN_NAME
ENV NEXT_PUBLIC_CHAIN_RPC_URL=$NEXT_PUBLIC_CHAIN_RPC_URL
ENV NEXT_PUBLIC_CHAIN_EXPLORER_NAME=$NEXT_PUBLIC_CHAIN_EXPLORER_NAME
ENV NEXT_PUBLIC_CHAIN_EXPLORER_URL=$NEXT_PUBLIC_CHAIN_EXPLORER_URL
ENV NEXT_PUBLIC_CHAIN_TESTNET=$NEXT_PUBLIC_CHAIN_TESTNET
ENV NEXT_PUBLIC_WALLETCONNECT_PROJECT_ID=$NEXT_PUBLIC_WALLETCONNECT_PROJECT_ID
ENV NEXT_PUBLIC_XBID_FACTORY_ADDRESS=$NEXT_PUBLIC_XBID_FACTORY_ADDRESS
ENV NEXT_PUBLIC_XBID_REGISTRY_ADDRESS=$NEXT_PUBLIC_XBID_REGISTRY_ADDRESS
ENV NEXT_PUBLIC_XBID_RISK_CONTROLLER_ADDRESS=$NEXT_PUBLIC_XBID_RISK_CONTROLLER_ADDRESS
ENV NEXT_PUBLIC_XBID_FEE_VAULT_ADDRESS=$NEXT_PUBLIC_XBID_FEE_VAULT_ADDRESS
ENV NEXT_PUBLIC_XBID_SETTLEMENT_TOKEN_ADDRESS=$NEXT_PUBLIC_XBID_SETTLEMENT_TOKEN_ADDRESS
ENV NEXT_PUBLIC_DEFAULT_CONTEST_ID=$NEXT_PUBLIC_DEFAULT_CONTEST_ID
RUN pnpm build

FROM node:22-alpine AS runner
WORKDIR /app
ENV NODE_ENV=production
ENV NEXT_TELEMETRY_DISABLED=1
ENV HOSTNAME=0.0.0.0
ENV PORT=3000
RUN addgroup --system --gid 1001 nodejs && adduser --system --uid 1001 nextjs
COPY --from=builder --chown=nextjs:nodejs /app/public ./public
COPY --from=builder --chown=nextjs:nodejs /app/.next/standalone ./
COPY --from=builder --chown=nextjs:nodejs /app/.next/static ./.next/static
USER nextjs
EXPOSE 3000
CMD ["node", "server.js"]
